### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by thesoldiersway** [codrops/ConnectedGrid#2]
This is very nice Manoela! Is it any possibility or solution u can suggest to get it work in one column on mobile? Best regards Kalle

**Comment by crnacura** [comment]
Thank you for the heads up Kalle, I totally forgot to make this grid responsive! Please have a look at the updated CSS, this will make sure there's just one column on smaller screens!

**Comment by thesoldiersway** [comment]
Thank you Manoela! You r amazing! I can´t wait for your new upcoming  ideas and works! Big thanks for everything! <3
